### ISSUE TITLE
Preview sync: preview dock scrolls to often

### ISSUE THREAD

**Issue by hlamer** [bjones1/enki#35]
I tried to use preview sync when editing long document. Whenever I move cursor up or down - preview dock scrolls to center text.
I like the idea of centering the preview dock, but if we do it on every move, it looks like annoying flickering.
Is it possible to scroll the preview dock only if highlighted line is not visible?

**Comment by bjones1** [comment]
That's a good idea. It should be fairly straightforward to look at the amount to scroll and have a minimum threshold before doing so. I'll take a look.

**Comment by bjones1** [comment]
Would you test my scrollTest branch, to see if that's what your were looking for? If so, I can clean that up and submit a pull request.

**Comment by hlamer** [comment]
Will try to test today or tomorrow

**Comment by hlamer** [comment]
`scrollTest` works much better, so I think it should be merged.
One more thing. When the preview dock is scrolled, highlighted text is usually on the first or on the last visible line of the text. I think it was centered for me when I opened this bug, but I don't remember on which document I tested it.
Is it possible to center the dock on the highlighted text?
It is not critical if text will not be exactly in the center. It is enough to show 3-5 lines above and below.

**Comment by bjones1** [comment]
Great! Let me add that feature, then do a bit more testing.

**Comment by bjones1** [comment]
My scattered thoughts on this revision:

- I prefer the "side-by-side" sync style. The main advantage is, of course, seeing the text and web views next to each other. The disadvantages: 
  - Scrolling is annoying, since there's a noticeable delay between when the text view scrolls and when the web view catches up with it. I don't see any easy workaround for this.
  - If the preview windows is above or below the text window, then it will always scroll to the top or bottom, limiting the viewable context. To fix this, use the mode below when in this case.
- So, to reduce the scrolling annoyance, I'll add a "center on sync mode" that centers the synced text in the preview window. A tolerance of +/- several lines will prevent this from scrolling too often.

Or, what about adding a tolerance to the sync: only re-sync (scroll the preview windows) if the preview and text views are more than x pixels apart? The tolerance would also keep synced text away from the top and bottom of the screen, to prevent unnecessary scrolling in those areas. A large tolerance value would therefore acts as a center-on-sync, but avoid scrolling until it was absolutely necessary.

If I take this course: I think I just need to add in a tolerance value, and do adjusting to the tolerance if it goes offscreen. Then, simply keep the preview scroll position if within the tolerance; otherwise, do calculations as usual, then adjust the result to lie in the middle of the tolerance.

**Comment by bjones1** [comment]
This seems to work. I'm closing this issue to continue the discussion at https://github.com/hlamer/enki/pull/266.
