### ISSUE TITLE
Hide preview progress for all non-sphinx files

### ISSUE THREAD

**Issue by hlamer** [bjones1/enki#36]
When I edit a small markdown file, my sight is distracted by continuous flickering of progress bar at the corner. Progress can be useful for multifile Sphinx project, but not for other preview types.
Let's hide preview bar for non-sphinx files.

**Comment by bjones1** [comment]
I agree that the "spinning" progress bar is distracting. My thoughts on this:

Pro:
* For reST / Sphinx files, it changes color if errors or warnings are found. I think this is helpful, so that I can immediately correct them without always checking the log window output.
* It does provide some indication that processing is ongoing. This *might* be helpful when editing big files. One example: the [PyInstaller manual](https://github.com/pyinstaller/pyinstaller/blob/develop/doc/source/Manual.rst) is almost 3000 lines. I'm not sure how long it takes to render this, but some indication that Enki is processing it might be helpful.

Cons:
* Markdown, as far as I can tell, never produces errors or warnings. So, a log window or even a color just takes space and is distracting.
* For files that are small (which is most files that users edit), the constant "spinning" is distracting.

Ideas:
* Avoid the "spinning" feature? Perhaps change the text to "processing" instead of a percentage, but have no other indication?
* Hide the progress bar for Markdown entirely? (But what about really big markdown files)?

What are your thoughts?

**Comment by hlamer** [comment]
I suggest to avoid spinning feature for any project except Sphinx.
PyInstaller manual renders in 2 seconds. Quite good even without the progress bar.

**Comment by bjones1** [comment]
Will do.

**Comment by bjones1** [comment]
Closed byhttps://github.com/hlamer/enki/pull/264.
