### ISSUE TITLE
Sphinx project settings usability - project path

### ISSUE THREAD

**Issue by hlamer** [bjones1/enki#37]
I tried to test Sphinx project now, but got lost what to enter in `Project path` input. (Yes, I used to knew it some time ago, but forgot). I didn't know, what to type here, project root, `conf.py` path, or something else.

If I understand correctly, it must be a path where `conf.py` is located. Rename the input to something more usable, like `Build configuration file (conf.py)`, and configure the file open dialog mask to open only `conf.py` file. Then you can get `os.path.dirname` from this file to get the path.

**Comment by bjones1** [comment]
The official name per the Sphinx documentation of this path is the source directory (see http://sphinx-doc.org/invocation.html, http://sphinx-doc.org/glossary.html#term-source-directory). While `conf.py` is located by default in the source directory, the -c option allows placing it in a separate directory (see http://sphinx-doc.org/invocation.html).

So, I don't find to prompt the user to find conf.py, since it's possible that's the wrong directory. Perhaps adding better docs (a tooltip?) would help?

**Comment by hlamer** [comment]
OK. Add a hint about `conf.py` file as an italic label. Like `Hint: you can configure ...` on the `Lint->Python` tab
